[package]
name = "cursive_example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1"
log = "0.4"

# cursive = "*"

[dependencies.cursive]
version = "*"
default-features = false
features = ["crossterm-backend", "toml"]

# [features]
# default = ["ncurses-backend"]
# ncurses-backend = ["cursive/ncurses-backend"]
# pancurses-backend = ["cursive/pancurses-backend"]
# termion-backend = ["cursive/termion-backend"]
# crossterm-backend = ["cursive/crossterm-backend"]
# blt-backend = ["cursive/blt-backend"]
